# Generated by Django 3.0.6 on 2021-09-10 03:32

import SmartDjango.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterField(
            model_name='config',
            name='key',
            field=SmartDjango.models.fields.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='value',
            field=SmartDjango.models.fields.CharField(max_length=255),
        ),
    ]
