# Generated by Django 2.0 on 2018-02-22 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('pwd_change_time', models.FloatField(blank=True, default=0, null=True)),
                ('grant', models.BooleanField(default=False, verbose_name='是否有权限新增用户')),
                ('port', models.IntegerField(default=0, verbose_name='SS端口')),
                ('ss_pwd', models.CharField(default=None, max_length=32, verbose_name='SS密码')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.User')),
            ],
        ),
    ]
