# Generated by Django 2.0 on 2018-02-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='port',
            field=models.SmallIntegerField(default=0, unique=True, verbose_name='SS端口'),
        ),
    ]
