# Generated by Django 2.0 on 2018-02-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20180222_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='port',
            field=models.PositiveSmallIntegerField(default=0, unique=True, verbose_name='SS端口'),
        ),
    ]
